### ISSUE TITLE
How to pass https to the regexp from the property cloud_controller_uri

### ISSUE THREAD

**Issue by francoisyanick** [cloudfoundry-community/admin-ui-boshrelease#21]
Hi,

I am getting a very odd error about missing https in my cf api url. But the thing is that it is present in my bosh deployment manifest so I am not so sure why it is not kept the way it is.

My bosh deployment manifest:
{code}
properties:
  [..]
  admin_ui:
    # admin_ui.cloud_controller_uri:
    #   description: "Full url of the Cloud Controller api"
    cloud_controller_uri: "https://api.mycf.com/"
  [..]
{code}

While I am getting this error in 

{code}
==> /var/vcap/sys/log/admin_ui/admin_ui.stderr.log <==
	from bin/admin:45:in `<main>'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/vendor/bundle/ruby/1.9.1/gems/membrane-1.1.0/lib/membrane/schemas/record.rb:81:in `fail!': { cloud_controller_uri => Value api.mycf.com doesn't match regexp /(http[s]?:\/\/[^\r\n\t]+)/ } (Membrane::SchemaValidationError)
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/vendor/bundle/ruby/1.9.1/gems/membrane-1.1.0/lib/membrane/schemas/record.rb:60:in `validate'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/vendor/bundle/ruby/1.9.1/gems/membrane-1.1.0/lib/membrane/schemas/record.rb:23:in `validate'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/lib/admin/config.rb:126:in `validate'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/lib/admin/config.rb:116:in `tap'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/lib/admin/config.rb:116:in `load'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/lib/admin.rb:49:in `setup_config'
	from /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-5e0de4828e32823539adc00197817e0f800583a8/admin_ui/lib/admin.rb:32:in `start'
	from bin/admin:45:in `<main>'

==> /var/vcap/sys/log/admin_ui/admin_ui.stdout.log <==
{code}

I have tried many variations to define the value of cloud_controller_uri: with or without quotes, single, double, http, https, etc. But all without success and generating that error every time.

I understand the error but don't understand why the error is happening! If somebody can help, this will be great.

Thx

**Comment by francoisyanick** [comment]
Please close this issue, my issue was not really one after all. The "https" value was well passed but I had another syntax somewhere else.

Thank you
