### ISSUE TITLE
This page requires data from services that are currently unavailable

### ISSUE THREAD

**Issue by mminges** [cloudfoundry-community/admin-ui-boshrelease#30]
I have deployed admin-ui-boshrelease v6 along with cf-release v225 on OpenStack. I also setup the admin-ui group and user using uaac as described here: https://github.com/cloudfoundry-incubator/admin-ui#setup-administration-ui-group-and-user-using-uaac. 
The admin-ui/0 VM has deployed successfully and I can connect with the admin credentials and can see tabs like DEA, Components, etc. However, most every other tab (Organizations, Spaces, Routes. etc. are shwoing "This page requires data from services that are currently unavailable."

After having ssh'd into the admin_ui VM and tailed `/var/vcap/sys/log/admin_ui/admin_ui.log`, I am seeing the following log output:
```
E, [2016-01-15T17:10:55.644274 #4133] ERROR -- : [ -- ] : [ -- ] : Error during discovery of organizations_private_domains: #<Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/postrgres>
E, [2016-01-15T17:10:55.652298 #4133] ERROR -- : [ -- ] : [ -- ] : /var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:96:in `require'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:96:in `load_adapter'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:26:in `adapter_class'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:45:in `connect'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.26.0/lib/sequel/core.rb:106:in `connect'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/lib/admin/cc.rb:643:in `select'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/lib/admin/cc.rb:583:in `discover'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/lib/admin/cc.rb:611:in `block in schedule'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/lib/admin/scheduled_thread_pool.rb:27:in `call'
/var/vcap/data/packages/admin_ui/dc07544c951469dffe507dc85d6c8f6a773b60a0.1-b0285c530cbc8a04b783297e8a872ae7bedbc622/admin_ui/lib/admin/scheduled_thread_pool.rb:27:in `block (2 levels) in initialize'
D, [2016-01-15T17:10:55.652360 #4133] DEBUG -- : [ -- ] : [ -- ] : Caching CC organizations_private_domains data.  Count: 0.  Retrieval time: 0.029995722 seconds
```
The following snippet from the log output above has me thinking this is a gem issue but I dont know enough to know for sure: `<Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/postrgres>`.

I don't see anything else from the admin_ui.log that would make me think that I have misconfigured my deployment manifest.

Any help would be greatly appreciated!

**Comment by mminges** [comment]
Closing this issue. I had a typo in `properties.admin_ui.ccdb.scheme` that was the root cause.
