### ISSUE TITLE
Error pulling events when using MySQL

### ISSUE THREAD

**Issue by jgprogramming** [cloudfoundry-community/admin-ui-boshrelease#58]
I'm getting an error while using Admin UI with mysql databases:

> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:6:in `rescue in <top (required)>'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:3:in `<top (required)>'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:98:in `require'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:98:in `load_adapter'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:28:in `adapter_class'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:47:in `connect'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/core.rb:108:in `connect'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/lib/admin/cc.rb:688:in `select'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/lib/admin/cc.rb:627:in `discover'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/lib/admin/cc.rb:656:in `block in schedule'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/lib/admin/scheduled_thread_pool.rb:27:in `call'
> /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/lib/admin/scheduled_thread_pool.rb:27:in `block (2 levels) in initialize'
> D, [2018-02-07T10:21:21.916672 #9630] DEBUG -- : [ -- ] : [ -- ] : Caching CC spaces_managers data.  Count: 0.  Retrieval time: 0.010503128 seconds
> E, [2018-02-07T10:21:21.917572 #9630] ERROR -- : [ -- ] : [ -- ] : Error during discovery of stacks: #<Sequel::AdapterNotFound: LoadError: cannot load such file -- mysql>
> E, [2018-02-07T10:21:21.919062 #9630] ERROR -- : [ -- ] : [ -- ] : /var/vcap/data/packages/admin_ui/1f823191bc8afcfa1264fd34429be94afe2e19d7/admin_ui/vendor/bundle/ruby/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:6:in `require

Is there any known fix for this?

**Comment by driogold** [comment]
None yet
